package com.banking.system.repository;

import com.banking.system.model.Transaction;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
 * Data Access interface for Transaction entity.
 */
@Repository
public interface TransactionRepository extends JpaRepository<Transaction, Long> {
    
    // Custom query method generated by Spring Data JPA implicitly 
    List<Transaction> findByAccountIdOrderByTransactionDateDesc(Long accountId);
}
